# Generated by Django 5.0.6 on 2024-05-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='membership_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='primary_membership_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
