# Generated by Django 5.0.6 on 2024-05-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userfaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfaves',
            name='itemInstanceId',
            field=models.CharField(max_length=255),
        ),
    ]
