# Generated by Django 5.0.6 on 2024-05-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userfaves_iteminstanceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfaves',
            name='itemInstanceId',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
