# Generated by Django 5.0.6 on 2024-06-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_oauthtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oauthtoken',
            name='token_type',
        ),
    ]
