# Generated by Django 5.0.6 on 2024-07-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_oauthtoken_token_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfaves',
            name='itemInstanceId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='userfaves',
            unique_together={('username', 'itemInstanceId')},
        ),
    ]
