# Generated by Django 5.0.6 on 2024-06-26 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubclassFragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subclass', models.CharField(max_length=50)),
                ('mobility_mod', models.IntegerField(default=0)),
                ('resilience_mod', models.IntegerField(default=0)),
                ('recovery_mod', models.IntegerField(default=0)),
                ('discipline_mod', models.IntegerField(default=0)),
                ('intellect_mod', models.IntegerField(default=0)),
                ('strength_mod', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ArmorOptimizationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exotic_id', models.CharField(max_length=100)),
                ('subclass', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArmorPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=100)),
                ('item_hash', models.CharField(max_length=100)),
                ('armor_type', models.CharField(max_length=20)),
                ('is_exotic', models.BooleanField(default=False)),
                ('mobility', models.IntegerField()),
                ('resilience', models.IntegerField()),
                ('recovery', models.IntegerField()),
                ('discipline', models.IntegerField()),
                ('intellect', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armor_pieces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
