# Generated by Django 5.0.6 on 2024-06-30 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armor_maxx', '0002_armormodifier_delete_subclassfragment'),
    ]

    operations = [
        migrations.AddField(
            model_name='armoroptimizationrequest',
            name='character_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armorpiece',
            name='character_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
