# Generated by Django 5.0.6 on 2024-07-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armor_maxx', '0003_armoroptimizationrequest_character_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorDefinition',
            fields=[
                ('item_hash', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tier_type', models.IntegerField()),
                ('item_type', models.CharField(max_length=50)),
                ('item_sub_type', models.CharField(max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['tier_type'], name='armor_maxx__tier_ty_be3b88_idx'), models.Index(fields=['item_type'], name='armor_maxx__item_ty_1e0202_idx')],
            },
        ),
    ]
