# Generated by Django 5.0.6 on 2024-07-01 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armor_maxx', '0004_armordefinition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='armordefinition',
            name='item_category_hashes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='armorpiece',
            name='class_type',
            field=models.CharField(choices=[('TITAN', 'Titan'), ('HUNTER', 'Hunter'), ('WARLOCK', 'Warlock'), ('ALL', 'All Classes')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armorpiece',
            name='inventory_type',
            field=models.CharField(choices=[('profile', 'Profile'), ('character', 'Character'), ('equipped', 'Equipped')], default=2, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='armorpiece',
            name='armor_type',
            field=models.CharField(choices=[('HELMET', 'Helmet'), ('GAUNTLETS', 'Gauntlets'), ('CHEST_ARMOR', 'Chest Armor'), ('LEG_ARMOR', 'Leg Armor'), ('CLASS_ARMOR', 'Class Armor')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='armorpiece',
            unique_together={('user', 'item_id', 'character_id')},
        ),
        migrations.AddIndex(
            model_name='armoroptimizationrequest',
            index=models.Index(fields=['user', 'character_id'], name='armor_maxx__user_id_ff1110_idx'),
        ),
        migrations.AddIndex(
            model_name='armoroptimizationrequest',
            index=models.Index(fields=['created_at'], name='armor_maxx__created_e92232_idx'),
        ),
        migrations.AddIndex(
            model_name='armorpiece',
            index=models.Index(fields=['user', 'character_id'], name='armor_maxx__user_id_550103_idx'),
        ),
        migrations.AddIndex(
            model_name='armorpiece',
            index=models.Index(fields=['armor_type'], name='armor_maxx__armor_t_def8a1_idx'),
        ),
        migrations.AddIndex(
            model_name='armorpiece',
            index=models.Index(fields=['class_type'], name='armor_maxx__class_t_9b412e_idx'),
        ),
        migrations.AddIndex(
            model_name='armorpiece',
            index=models.Index(fields=['is_exotic'], name='armor_maxx__is_exot_d66387_idx'),
        ),
    ]
