# Generated by Django 5.0.6 on 2024-05-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefinitionTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('table', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('content', models.JSONField()),
            ],
        ),
    ]
